# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

Category.create!(name: "Vegetables", position: "1")
Category.create!(name: "Fruits", position: "1")
Category.create!(name: "Cheeses", position: "1")
Category.create!(name: "Bread", position: "1")
Category.create!(name: "Milk", position: "1")
Category.create!(name: "Wine", position: "1")
Category.create!(name: "Ice cream", position: "1")
Category.create!(name: "Candies", position: "1")

Product.create!(name: "Candies "Cowka"", price: 125.49, description: "Sugar, condensed milk product (skimmed milk (27%), sugar, milk fat substitute", position: "1", category_id: 9)
Product.create!(name: "Candies "Bim-Bom"", price: 107.99, description: "Molasses, sugar, acidity regulator mixture of lactic and citric acids, concentrated juices (0.3%)", position: "1", category_id: 9)
Product.create!(name: "Candies "Bees"", price: 182.0, description: "Jelly candy Crazy bee frutti Roshen", position: "1", category_id: 9)
Product.create!(name: "Ice cream "Ice cake"", price: 29.9, description: "There is no such thing as too much chocolate - connoisseurs of "Lasunka" ice cream know this for sure. Ice cream is the new cake.", position: "1", category_id: 8)
Product.create!(name: "Chocolate ice cream", price: 28.0, description: "Chocolate ice cream is ice cream with natural or artificial chocolate flavoring.", position: "1", category_id: 8)
Product.create!(name: "Wine "Pirosmani"", price: 173.5, description: "Wine materials are processed fortified strong special type white port wines with the addition of rectified ethyl alcohol, sulfur dioxide antioxidant", position: "1", category_id: 7)
Product.create!(name: "Wine "Caballeros"", price: 167.8, description: "Tempranillo grape wine, sulphites. Loranzo. Spain.", position: "1", category_id: 7)
Product.create!(name: "Bread "Agro"", price: 19.9, description: "High-grade wheat flour, drinking water, white crystalline sugar, table margarine (composition: vegetable oils (sunflower, palm and their fractions)", position: "1", category_id: 5)
Product.create!(name: "Bread "Miracle"", price: 21.9, description: "Peeled rye flour, first grade wheat flour, drinking water, sugar syrup, (white sugar, water, fermented wort concentrate (rye, fermented rye malt, barley malt)", position: "1", category_id: 5)
Product.create!(name: "Bread "Agrola"", price: 22.9, description: "Wheat flour of the first grade, wheat flour of the highest grade, drinking water, pressed baker's yeast, table salt, white sugar", position: "1", category_id: 5)
Product.create!(name: "Cheese "Goladnia"", price: 69.9, description: "Cheese cut into slices is suitable for outdoor recreation, so that you don't have to deal with a whole piece for a long time.", position: "1", category_id: 4)
Product.create!(name: "Cheese "Blue"", price: 599.0, description: "Generic term used to describe cheese produced with pasteurized cow's, sheep's, or goat's milk and ripened with cultures of the mold penicillium.	", position: "1", category_id: 4)
Product.create!(name: "Cheese "Prostokvas"", price: 65.3, description: "Cheese is the healthiest snack. It is useful to eat with berries, fruits, sweet toppings and nuts. Salted with garlic and greens will also be delicious.	", position: "1", category_id: 4)
Product.create!(name: "Kiwi", price: 110.95, description: "Kiwi is an interesting fruit with a hairy skin, the benefits of which are underestimated. It contains antioxidants and has antiseptic properties.", position: "1", category_id: 2)
Product.create!(name: "Lemons", price: 57.55, description: "Lemon is the best citrus tree. Juicy, bright, hangs on a branch and invites you to pluck it. Lemon is known not only for its taste, but also for its incredible benefits.", position: "1", category_id: 2)
Product.create!(name: "Apples", price: 28.95, description: "Apple is a very useful fruit that is used in cooking and cosmetology. Idared apples were bred almost 100 years ago by crossing the most popular varieties: Warboy and Jonathan.", position: "1", category_id: 2)
Product.create!(name: "Bananas", price: 62.9, description: "Yellow fruit with a thick skin and soft sweet flesh.", position: "1", category_id: 2)
Product.create!(name: "Beet", price: 6.89, description: "If in pursuit of good health you have already tried many organic vegetables and fruits and remained unsatisfied, then you should pay attention to beets. This is a natural product that is available to everyone.", position: "1", category_id: 1)
Product.create!(name: "Onion", price: 42.9, description: "Green onions are also called salad onions, because they are so nice to crunch in the first spring salad. Onions are rich in vitamins, minerals and antioxidants.", position: "1", category_id: 1)
Product.create!(name: "Сabbages", price: 25.69, description: "Energy value (calorie) per 100g: 27 kcal. Nutritional value per 100g: Proteins - 1.8g, fats - 0.1g, carbohydrates - 4.7g. Storage conditions: at a temperature of +2-+4 ˚С.", position: "1", category_id: 1)
Product.create!(name: "Potatoes in nets", price: 17.95, description: "What do we know about potatoes? This is a tuberous plant from the genus Solanaceae. It is very tasty and nutritious. And what do we know about potatoes in ATB? It ends quickly, because you will not be able to buy such delicious potatoes anywhere else.", position: "1", category_id: 1)
Product.create!(name: "Potatoes washed", price: 22.95, description: "Many of us love baked potatoes with aromatic herbs, or mashed potatoes, or fried with onions, or zrazy with meat. The main ingredient for these dishes is the queen of the garden - the potato.", position: "1", category_id: 1)
Product.create!(name: "Carrots", price: 56.95, description: "Carrot is the most useful and bright vegetable. We are most used to seeing orange carrots. But it is also yellow, white and purple. It has such a shade due to the presence of anthocyanin. It is he who helps fight cardiovascular diseases.", position: "1", category_id: 1)
Product.create!(name: "Cucumbers", price: 78.89, description: "Cucumbers are a very tasty and nutritious product. They contain 90% water, so they are also an excellent example of a dietary product. Goes well with protein dishes. They are combined with vegetables and greens, ideal to add to salads and make snacks.", position: "1", category_id: 1)
Product.create!(name: "Tomatoes", price: 66.89, description: "Tomatoes grown in a greenhouse can compete and win over other tomatoes because they are tastier, fresher and healthier. They grow in ideal temperature conditions with constant watering.", position: "1", category_id: 1)
Product.create!(name: "Potatoes", price: 9.27, description: "They get soft and fluffy when cooked, so they're the best potatoes for baking, mashing, and frying, as well as in soups and casseroles.", position: "1", category_id: 1)
Product.create!(name: "Bread 'Agrola G'", price: 15.99, description: "Is a long, thin type of bread of French origin that is commonly made from basic lean dough (the dough, though not the shape, is defined by French law).", position: "1", category_id: 5)
Product.create!(name: "Milk 'Homemade'", price: 36.0, description: "Is an emulsion or colloid of butterfat globules within a water-based fluid that contains dissolved carbohydrates and protein aggregates with minerals.", position: "1", category_id: 6)
